# Site settings
title: Chris Dundon - Metamorphasis
header-img: img/home-bg.png
email: chris.dundon@gmail.com
copyright_name: cpdundon
description: > # this means to ignore newlines until "baseurl:"
  The story of my transition into web development
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: chrisDundon
github_username:  cpdundon
learn_profile: cpdundon
email_username: chris.dundon@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
